/**
 * Phase 2 — Sport Detail Page (/sports/:slug)
 * PRD §5.7: 5 pillars per sport — Learn, Movement Science, Injury Prevention, Training, Recovery
 * Full content for Table Tennis and Football (PRD Phase 2 Week 5-6 deliverable).
 */

import { useState } from 'react'
import { useParams, Link, Navigate } from 'react-router-dom'
import { ArrowRight, Clock, BookOpen, Shield, Zap, RefreshCw, Lock, ChevronRight } from 'lucide-react'
import { NodeLine, PillTag, FuturisticCard, SectionHeader } from '@/components/ui/FuturisticElements'
import { Button } from '@/components/ui/Button'
import { cn } from '@/lib/utils'

/* ── PRD §5.7 Pillar definitions ─────────────────────── */
const PILLARS = [
  { id: 'learn',     label: 'Learn the Sport',    icon: BookOpen,  color: '#606C38' },
  { id: 'movement',  label: 'Movement Science',    icon: Zap,       color: '#264653' },
  { id: 'injury',    label: 'Injury Prevention',   icon: Shield,    color: '#8a9c4a' },
  { id: 'training',  label: 'Training',            icon: Zap,       color: '#4A6FA5' },
  { id: 'recovery',  label: 'Recovery',            icon: RefreshCw, color: '#606C38' },
]

/* ── Sport content database ───────────────────────────── */
const SPORT_DATA: Record<string, {
  name: string
  icon: string
  tagline: string
  keyStats: { label: string; value: string }[]
  pillars: Record<string, {
    intro: string
    lessons: { title: string; duration: string; type: string; preview: boolean; body: string }[]
    keyPoints: string[]
  }>
}> = {
  'table-tennis': {
    name: 'Table Tennis',
    icon: '🏓',
    tagline: 'Wrist mechanics, footwork biomechanics, shoulder science, and injury prevention for serious players.',
    keyStats: [
      { label: 'Primary joints at risk', value: 'Shoulder · Wrist · Elbow' },
      { label: 'Dominant movement', value: 'Forearm pronation + wrist snap' },
      { label: 'Top injury site', value: 'Rotator cuff' },
    ],
    pillars: {
      learn: {
        intro: 'Table tennis technique built on biomechanical principles — not just "hit the ball harder."',
        keyPoints: [
          'Topspin is generated by racket-face angle + wrist snap, not arm strength',
          'Footwork efficiency determines shot quality more than upper body technique',
          'The pendulum serve creates deceptive spin through forearm rotation mechanics',
          'Backhand flick relies on elbow as a fixed pivot with explosive forearm rotation',
        ],
        lessons: [
          {
            title: 'The Science of the Table Tennis Forehand',
            duration: '8 min',
            type: 'Movement Science',
            preview: true,
            body: 'The forehand topspin is the most powerful shot in table tennis — and the most biomechanically complex. The stroke begins with hip rotation, transfers energy through trunk rotation, and delivers it via shoulder internal rotation and forearm pronation into a wrist snap at contact.\n\nKey mechanics:\n• Hip-to-shoulder kinetic chain — 60% of forehand power comes from lower body rotation\n• Contact point: ball just past peak of bounce, racket face at 75-80° to horizontal\n• Wrist snap: the final acceleration, generating topspin via downward brush\n• Elbow position: 90-110° at contact, acting as a rotating hinge\n\nCommon technical faults and their biomechanical cause:\n• Flat hitting (no topspin) → wrist is rigid at contact\n• Inconsistent depth → contact point too early (ball rising) or too late\n• Shoulder pain after high volume → over-reliance on shoulder rotation instead of hip drive',
          },
          {
            title: 'Wrist Mechanics: How Topspin is Generated',
            duration: '6 min',
            type: 'Movement Science',
            preview: true,
            body: 'Topspin in table tennis is a function of racket-face angle and the velocity of brush contact, not arm speed. The wrist plays a critical role in the final milliseconds of stroke contact.\n\nThe physics:\n• Magnus effect: topspin creates downward aerodynamic force, bringing the ball down faster and bouncing it higher on the opponent\'s side\n• Generating topspin: racket face angled forward (60-70°) and moving upward at contact\n• Wrist pronation adds rotational velocity beyond what forearm alone can generate\n\nWrist health in TT:\nRecreational players often develop medial epicondylitis (inner elbow pain) from excessive wrist use without adequate forearm strength. See the Injury Prevention pillar for the wrist strengthening protocol.',
          },
          {
            title: 'Footwork Patterns and Court Positioning',
            duration: '7 min',
            type: 'Technique',
            preview: false,
            body: 'Footwork is the foundation of consistency in table tennis. Even technically perfect strokes will break down under pressure if your base position is wrong.\n\nCore footwork principles:\n• Athlete stance: weight slightly forward, knees bent, feet shoulder-width apart\n• The crossover step for wide balls (not side shuffle — too slow)\n• Return to neutral position after every shot\n\nPositioning zones:\n• Close position (0.5-1m): blocking, counter-topspin, fast exchanges\n• Mid position (1-1.5m): topspin rallies, primary attacking position\n• Far position (1.5m+): defensive lob, loop recovery',
          },
          {
            title: 'The Pendulum Serve — Biomechanics of Deception',
            duration: '5 min',
            type: 'Technique',
            preview: false,
            body: 'The pendulum serve is one of the most effective serves in table tennis because it disguises spin direction through forearm rotation mechanics.\n\nThe serve works by:\n• Forearm pronation during contact creates sidespin\n• Wrist angle at contact determines whether it\'s sidespin, backspin, or nospin\n• The racket path looks the same to the opponent regardless of spin type\n\nBiomechanically, the pendulum serve uses the same forearm rotation mechanics as the forehand — making it a natural serve for players who already have good forehand mechanics.',
          },
          {
            title: 'Understanding Injury Risk in Recreational TT',
            duration: '9 min',
            type: 'Injury Prevention',
            preview: false,
            body: 'Recreational table tennis players have a surprisingly high rate of overuse injuries — precisely because the sport looks low-intensity but involves thousands of repetitive joint movements per session.\n\nCommon injuries in recreational TT:\n• Rotator cuff tendinopathy (shoulder): from shoulder internal rotation repetition without adequate warmup or posterior capsule stretching\n• Medial epicondylitis (elbow): from forearm pronation overload, especially in players generating topspin with wrist rather than hip rotation\n• Wrist TFCC irritation: from high-volume backspin serves and chop shots\n\nPrevention is the only treatment that matters. See the Injury Prevention pillar for the evidence-based TT warmup protocol.',
          },
        ],
      },
      movement: {
        intro: 'The biomechanics behind table tennis performance — what your joints are actually doing during every stroke.',
        keyPoints: [
          'The shoulder performs internal rotation at ~500°/sec during a forehand — close to throwing sports',
          'Wrist pronation velocity is the primary driver of topspin, not arm speed',
          'Centre of gravity must stay over base of support throughout all footwork patterns',
          'The elbow acts as a lever fulcrum in backhand strokes — keeping it fixed multiplies racket speed',
        ],
        lessons: [
          {
            title: 'Shoulder Joint Mechanics in Table Tennis',
            duration: '10 min',
            type: 'Biomechanics',
            preview: true,
            body: 'The shoulder complex in table tennis is under repetitive load that most recreational players underestimate. During a forehand topspin, the shoulder undergoes internal rotation at angular velocities comparable to overhead throwing sports — yet is treated by most players as a low-risk joint.\n\nKey structures:\n• Rotator cuff (supraspinatus, infraspinatus, subscapularis, teres minor) — controls shoulder stabilisation\n• Posterior capsule — tightness here restricts internal rotation range and shifts load to passive structures\n• AC joint — stressed by the crossing arm pattern in backhand strokes\n\nBiomechanical risk factors:\n• Excessive reliance on shoulder rotation instead of hip-to-trunk drive\n• Poor scapular control during backswing\n• Playing through posterior shoulder tightness without addressing it',
          },
          {
            title: 'Force Vectors and the Kinetic Chain',
            duration: '8 min',
            type: 'Biomechanics',
            preview: false,
            body: 'Every stroke in table tennis is a kinetic chain event — power generated at the ground travels through the legs, hip, trunk, shoulder, elbow, wrist, and into the racket. Breaking the chain at any point reduces power and increases joint stress at the break point.\n\nThe forehand kinetic chain:\n1. Ground reaction force — push through the outside foot\n2. Hip rotation — drives trunk\n3. Trunk rotation — loads shoulder\n4. Shoulder internal rotation\n5. Forearm pronation\n6. Wrist snap at contact\n\nA player generating topspin primarily from the wrist without adequate hip and trunk contribution is breaking the kinetic chain — and overloading the distal joints as compensation.',
          },
        ],
      },
      injury: {
        intro: 'Expert-verified warmup protocols and injury prevention strategies specific to table tennis.',
        keyPoints: [
          'Pre-session shoulder warmup takes 8 minutes and reduces rotator cuff injury risk significantly',
          'Posterior capsule stretching is the single most effective TT shoulder injury prevention exercise',
          'Forearm flexor strengthening prevents medial epicondylitis in high-volume players',
          'Progressive loading — don\'t go straight into match-speed topspin rallies from cold',
        ],
        lessons: [
          {
            title: 'The 8-Minute Table Tennis Shoulder Warmup Protocol',
            duration: '8 min',
            type: 'Protocol',
            preview: true,
            body: '## Expert-Reviewed Protocol — Dr. Ananya Sharma, MPT (Sports)\n\nThis warmup targets the specific structures loaded in table tennis: rotator cuff, posterior capsule, scapular stabilisers, and forearm pronators.\n\n### Phase 1: Circulation (2 min)\n- Arm circles: 30 sec forward, 30 sec back, each arm\n- Shoulder shrugs with rotation: 30 reps\n- Band pull-aparts: 20 reps (if band available)\n\n### Phase 2: Mobility (3 min)\n- Cross-body shoulder stretch (posterior capsule): 30 sec each side × 2\n- Doorway chest opener: 30 sec × 2\n- Wrist circles: 30 sec each direction\n- Forearm pronation/supination: 20 reps each\n\n### Phase 3: Activation (3 min)\n- External rotation with band: 15 reps each arm\n- Side-lying external rotation: 12 reps each arm\n- Scapular wall slides: 10 reps\n\n**Do not skip this if you have a history of shoulder pain. The posterior capsule stretch alone takes 60 seconds and addresses the most common mechanical cause of TT shoulder pain.**',
          },
          {
            title: 'Elbow and Wrist Protection for High-Volume Players',
            duration: '6 min',
            type: 'Protocol',
            preview: false,
            body: 'Players who train 3+ sessions per week are at elevated risk of medial epicondylitis (golfer\'s elbow) and TFCC wrist injury.\n\nPrevention protocol:\n• Reverse wrist curls: 3 × 15 — strengthens the extensor compartment that counterbalances forearm pronation load\n• Eccentric wrist extension: 3 × 12 — evidence-backed for tendinopathy prevention\n• Grip strength work: farmer carries, dead hangs — builds load tolerance in forearm flexors\n• Rest between sessions: minimum 24 hours for forearm recovery\n\nWarning signs to stop playing immediately:\n• Localised pain over medial epicondyle during pronation\n• Wrist clicking with pain (TFCC sign — needs physio assessment)',
          },
        ],
      },
      training: {
        intro: 'Sport-supplementary training designed specifically to support table tennis performance and protect key joints.',
        keyPoints: [
          'Table tennis players need rotator cuff strength training — not just cardio',
          'Core rotational power directly transfers to forehand and backhand power',
          'Lower body work (squats, lunges) supports the explosive footwork demands of TT',
          'Training should not conflict with match days — schedule strength work post-session or on rest days',
        ],
        lessons: [
          {
            title: 'The Table Tennis Supplementary Training Plan',
            duration: '12 min',
            type: 'Training Plan',
            preview: true,
            body: '## PRD §5.3 Sport-Supplementary Plan — Table Tennis\n\nThis plan is designed for 2 gym sessions/week alongside 2-3 table tennis sessions. The goal is to strengthen the structures most loaded in TT without adding unnecessary fatigue to match performance.\n\n### Session A — Upper Body + Core\n1. Band pull-aparts: 3 × 20 (warmup)\n2. Dumbbell external rotation: 3 × 15 each\n3. Cable face pulls: 3 × 15\n4. Dumbbell shoulder press: 3 × 10 (moderate weight)\n5. Pallof press: 3 × 12 each side (anti-rotation core)\n6. Russian twists: 3 × 20 (rotational power)\n7. Dead hang: 3 × 20 sec (forearm and shoulder stability)\n\n### Session B — Lower Body + Rotational Power\n1. Goblet squat: 3 × 12\n2. Reverse lunge: 3 × 10 each leg\n3. Lateral band walks: 3 × 15 each direction\n4. Cable woodchop: 3 × 12 each side (hip-to-shoulder rotational power)\n5. Single-leg RDL: 3 × 10 each (balance + hamstring)\n6. Calf raises: 3 × 20 (ankle stability for TT footwork)\n\n**Progression:** Add load every 2 weeks. Deload (reduce volume by 40%) every 4th week.',
          },
        ],
      },
      recovery: {
        intro: 'Recovery protocols for table tennis — managing shoulder load, forearm fatigue, and return-to-play after injury.',
        keyPoints: [
          'Forearm fatigue is the limiting factor after high-volume TT sessions — 24-hour minimum recovery',
          'Cold water immersion for arms post-competition reduces delayed onset muscle soreness',
          'Shoulder deloading: one session per week at 50% intensity prevents cumulative overload',
          'Sleep is the single highest-ROI recovery tool — 8+ hours correlates with 40% lower injury risk in racket sports',
        ],
        lessons: [
          {
            title: 'Post-Session Recovery for Table Tennis',
            duration: '5 min',
            type: 'Recovery Protocol',
            preview: true,
            body: '## Immediate Post-Session (within 30 min)\n1. Forearm cold immersion: submerge forearms in cold water 10-12°C for 10 min\n2. Posterior shoulder stretch: 60 sec each side\n3. Wrist flexor stretch: 30 sec each side\n4. Protein intake: 20-30g within 30 min of session (supports muscle repair)\n\n## Same-Evening\n- Sleep target: 8+ hours\n- Avoid heavy grip work (no heavy lifting the evening after TT)\n\n## Next-Day Active Recovery (if training again)\n- 10-minute shoulder mobility sequence before next session\n- If shoulder is sore or tight: reduce volume by 50%, no forehand topspin training',
          },
        ],
      },
    },
  },

  'football': {
    name: 'Football / Soccer',
    icon: '⚽',
    tagline: 'ACL prevention, hamstring mechanics, sprint biomechanics, and sport-supplementary training for footballers.',
    keyStats: [
      { label: 'Primary joints at risk', value: 'Knee · Ankle · Hip' },
      { label: 'Highest injury risk', value: 'Non-contact ACL · Hamstring strain' },
      { label: 'Dominant movement', value: 'Multi-directional sprint + change of direction' },
    ],
    pillars: {
      learn: {
        intro: 'Football technique grounded in biomechanics — how body mechanics affect every pass, shot, and defensive action.',
        keyPoints: [
          'Hamstring strain during sprinting is the most common football injury — 90% occur in the late swing phase',
          'ACL tears are predominantly non-contact, occurring during deceleration and change of direction',
          'Passing technique depends on hip angle and ankle lock at contact, not foot speed',
          'Heading mechanics require neck flexor activation to absorb force — critical for concussion risk reduction',
        ],
        lessons: [
          {
            title: 'Sprint Mechanics and the Hamstring Load Problem',
            duration: '9 min',
            type: 'Movement Science',
            preview: true,
            body: 'Hamstring strains are the most common match injury in football — accounting for 12-17% of all injuries. The critical insight from sports science is that they almost always occur during the late swing phase of sprinting, when the hamstring is eccentrically loaded at its longest length.\n\nThe biomechanics of hamstring strain:\n• During sprinting, the hamstring must simultaneously contract (to decelerate the swinging leg) while being stretched (the leg is fully extended forward)\n• This eccentric load at full stretch is the highest-risk moment\n• Fatigue increases risk significantly — most hamstring strains occur in the final 20 minutes of each half\n\nRisk factors in recreational footballers:\n• Poor hip flexor flexibility (increases hamstring stretch at late swing)\n• Insufficient hamstring eccentric strength (Nordic curl benchmark: 3 × 6 bodyweight)\n• Inadequate warmup — cold hamstrings have lower tensile strength\n• Previous hamstring injury — the scar tissue at the prior tear site is the most common re-injury location',
          },
          {
            title: 'ACL Injury Prevention — What Every Footballer Should Know',
            duration: '10 min',
            type: 'Injury Prevention',
            preview: true,
            body: 'The ACL (anterior cruciate ligament) is the most feared injury in football — and 70% of ACL tears are non-contact, meaning they are preventable with the right training.\n\nHow non-contact ACL tears happen:\n• Planting foot and cutting sharply, usually at high speed\n• Landing from a header with knee in valgus (collapsing inward)\n• Decelerating suddenly with poor hip-knee-ankle alignment\n\nThe biomechanical risk factors:\n• Knee valgus during landing (the most preventable risk factor)\n• Weak hip abductors and external rotators (let the knee collapse inward)\n• Poor neuromuscular control — the brain doesn\'t stabilise the joint fast enough\n\nThe FIFA 11+ protocol has been shown in randomised controlled trials to reduce ACL injury risk by 50% in female footballers and 30% in male footballers. It takes 15-20 minutes and is included in the Injury Prevention pillar.',
          },
          {
            title: 'Passing Technique — Hip Mechanics and Ankle Lock',
            duration: '6 min',
            type: 'Technique',
            preview: false,
            body: 'Accurate passing is determined by hip alignment at the plant foot and the rigidity of the ankle at contact — not by how hard you kick.\n\nThe biomechanics of an accurate instep pass:\n1. Plant foot direction: points toward target, 15-20cm beside the ball\n2. Hip angle at contact: body leaning slightly over the ball\n3. Ankle lock: foot in fixed plantarflexion — a floppy ankle creates inconsistent contact surface\n4. Follow-through: toward target, maintaining balance on plant foot\n\nA rigid ankle at contact is what separates a crisp pass from a mishit. Players with hypermobile ankles often benefit from ankle strengthening work (single-leg calf raises, ankle circles with resistance).',
          },
          {
            title: 'The Pre-Season Football Conditioning Plan',
            duration: '11 min',
            type: 'Training Plan',
            preview: false,
            body: 'Pre-season conditioning for footballers has a specific goal: rebuild fitness without spiking injury risk from a training monotony response.\n\nWeeks 1-2: Base\n• Low-intensity runs: 3 × 30 min (70% max HR)\n• Bodyweight strength: squats, lunges, Nordic curls (3 × 6), planks\n• No ball work until Week 2\n\nWeeks 3-4: Acceleration\n• Interval runs: 6 × 4 min at 80%, 2 min rest\n• Add ball work: passing circuits, first touch\n• Strength: add load to squats and lunges\n\nWeeks 5-6: Sharpening\n• 5v5 and 7v7 sessions\n• Sprint work: 10 × 30m with full recovery\n• Strength maintenance: 2 sessions/week at 70% volume',
          },
          {
            title: 'Returning from a Hamstring Strain',
            duration: '8 min',
            type: 'Recovery Protocol',
            preview: false,
            body: 'Hamstring strain is the most common re-injury in football. The primary reason is returning too early — scar tissue forms faster than true tissue repair.\n\nReturn-to-play criteria (not time-based — performance-based):\n1. No pain on palpation at injury site\n2. Full range of motion under load\n3. Nordic curl: can complete 3 × 6 reps with equal force both legs\n4. Single-leg hop test: >90% limb symmetry index\n5. Progressive running: walk → jog → 70% sprint → 90% sprint → change of direction\n\nDo not return based on calendar days. Re-injury rate for premature return is 30-50%.',
          },
        ],
      },
      movement: {
        intro: 'The biomechanics of football movement — sprinting, changing direction, jumping, and the mechanics of injury.',
        keyPoints: [
          'Change of direction mechanics: hip angle, centre of gravity, and plant foot angle all predict injury risk',
          'Heading requires cervical stabilisation — weak neck flexors increase concussion force transmission',
          'The single-leg squat is the most reliable indicator of knee valgus risk on the pitch',
          'Sprint mechanics in football differ from athletics — acceleration is more important than top speed',
        ],
        lessons: [
          {
            title: 'Change of Direction Biomechanics and ACL Risk',
            duration: '9 min',
            type: 'Biomechanics',
            preview: true,
            body: 'The biomechanics of cutting and change of direction in football are where most non-contact ACL injuries occur. Understanding the mechanics makes prevention training more intuitive.\n\nSafe cut technique:\n• Plant foot angles 30-45° to direction of travel\n• Hip is aligned over knee over ankle at ground contact\n• Centre of gravity is low during the cut\n• Eyes up — allows earlier preparation for the cut\n\nRisky cut technique:\n• Upright posture at ground contact (high CoG)\n• Knee valgus at plant (knee inside the ankle)\n• Reactive cut (responding to ball, opponent) rather than planned\n\nThe physical qualities that protect against ACL injury in cutting:\n• Hip abductor and external rotator strength (prevents valgus collapse)\n• Hamstring strength (shares ACL load during knee loading)\n• Neuromuscular control — trained via single-leg squat and landing mechanics work',
          },
        ],
      },
      injury: {
        intro: 'Evidence-based injury prevention for footballers — the FIFA 11+ protocol and sport-specific warmup science.',
        keyPoints: [
          'FIFA 11+ reduces overall injury risk by 30-50% — it is the most evidence-based warmup protocol in any sport',
          'Nordic curl is the most effective single exercise for hamstring injury prevention (50% reduction in RCTs)',
          'Ankle proprioception training reduces ankle sprain risk by 60% in high-risk athletes',
          'The knee valgus test (single-leg squat) should be part of every footballer\'s pre-season screening',
        ],
        lessons: [
          {
            title: 'The FIFA 11+ Warmup — Full Protocol Breakdown',
            duration: '12 min',
            type: 'Protocol',
            preview: true,
            body: '## FIFA 11+ Protocol (15-20 minutes)\nEvidence: Reduces injury risk 30-50% in RCTs. Compulsory for all MotionLab football training plans.\n\n### Part 1: Running (8 min)\n1. Jogging in straight lines: 2 min\n2. Hip abduction/adduction whilst jogging: 90 sec\n3. Hip external/internal rotation whilst jogging: 90 sec\n4. Partner exercises: jogging with shoulder contact: 2 min\n\n### Part 2: Strength, Plyometric & Balance (10 min)\n5. Nordic hamstring curls: 2-3 × 6-8 reps ← MOST IMPORTANT\n6. Single-leg balance: 3 × 30 sec each leg\n7. Dynamic lunges with trunk rotation: 3 × 5 each\n8. Lateral hops with stabilisation: 3 × 5 each\n9. Squat jumps: 2 × 10\n10. Vertical jumps with proper landing: 2 × 10\n\n### Part 3: Running (2 min)\n11. Progressive speed runs: easy → fast → sprint\n\n**Key: Parts 1-3 must be done in order. Do not skip Part 2 — this is where the protective benefit is derived.**',
          },
          {
            title: 'Hamstring Injury Prevention — The Nordic Curl Protocol',
            duration: '7 min',
            type: 'Protocol',
            preview: false,
            body: 'The Nordic hamstring curl (NHC) is the single most evidence-backed injury prevention exercise in football. Two RCTs show it reduces hamstring strain incidence by 50% when performed consistently.\n\nHow to perform the Nordic curl:\n1. Kneel on soft surface, feet anchored by partner or under bar\n2. Body upright, hands by sides or crossed at chest\n3. Lower body toward ground with eccentric hamstring control\n4. Catch yourself with hands when you can no longer control the descent\n5. Return to upright using concentric contraction OR push up with hands\n\nProgression (8-week protocol for footballers):\n• Weeks 1-2: 2 × 5 reps (focus on slow, controlled descent)\n• Weeks 3-4: 3 × 6 reps\n• Weeks 5-6: 3 × 8 reps\n• Weeks 7-8: 3 × 10 reps\n\nDo not progress if you cannot control the descent for at least 3 seconds.',
          },
        ],
      },
      training: {
        intro: 'Sport-supplementary strength and conditioning for footballers — building the physical qualities the game demands.',
        keyPoints: [
          'Footballers need eccentric hamstring strength, hip abductor strength, and ankle stability — these are trainable',
          'Lower body strength training reduces injury risk AND improves sprint speed and change-of-direction',
          'Core anti-rotation strength improves passing power and reduces spinal load during shooting',
          'Periodise training around the match schedule — heavy strength work should not fall within 48 hours of a match',
        ],
        lessons: [
          {
            title: 'The Football Supplementary Strength Plan',
            duration: '10 min',
            type: 'Training Plan',
            preview: true,
            body: '## PRD §5.3 Sport-Supplementary Plan — Football\n\n2 gym sessions/week alongside 2-3 football sessions. Designed around the physical demands of multi-directional sprint sport.\n\n### Session A — Lower Body Strength + ACL Prevention\n1. Goblet squat: 3 × 10\n2. Bulgarian split squat: 3 × 8 each leg (develops single-leg power and balance)\n3. Nordic hamstring curl: 3 × 6-8 (non-negotiable for hamstring protection)\n4. Hip thrust: 3 × 12 (glute strength → knee valgus protection)\n5. Lateral band walk: 3 × 15 each direction (hip abductor activation)\n6. Ankle alphabet: 2 × 1 set each ankle (proprioception)\n7. Single-leg calf raise: 3 × 15 each (Achilles tendon load tolerance)\n\n### Session B — Explosive Power + Core\n1. Box jump: 3 × 5 (landing mechanics focus — soft landing, knee tracking)\n2. Lateral bound: 3 × 6 each (change of direction power)\n3. Barbell Romanian deadlift: 3 × 8 (posterior chain)\n4. Pallof press: 3 × 12 each side\n5. Copenhagen plank: 3 × 20 sec each (groin/adductor — most neglected football muscle)\n6. Dead bug: 3 × 10 each (core stability)\n\n**Periodisation:** Reduce Session A volume to 50% in the 48h before a match. Full volume on days 3+ post-match.',
          },
        ],
      },
      recovery: {
        intro: 'Post-match and post-training recovery protocols for footballers — accelerating readiness for the next session.',
        keyPoints: [
          'Match recovery priority: glycogen replenishment within 30 min (carbs + protein), hydration, sleep',
          'Cold water immersion (10-12°C, 10-15 min) reduces DOMS after high-intensity football sessions',
          'Active recovery (light jog, 15-20 min) the day after a match outperforms passive rest for readiness',
          'Hamstring flexibility does not improve long-term from static stretching post-session — focus on eccentric strength instead',
        ],
        lessons: [
          {
            title: 'Post-Match Recovery Protocol',
            duration: '6 min',
            type: 'Recovery Protocol',
            preview: true,
            body: '## Immediate Post-Match (0-30 min)\n1. Hydration: 500ml water + electrolytes within 15 min of final whistle\n2. Nutrition: 20-30g protein + 60-80g carbs within 30 min (e.g. chicken rice or protein shake + banana)\n3. Cold water immersion: 10-15 min at 10-12°C (legs only)\n4. Light quadriceps and hip flexor stretch: 30 sec each\n\n## Next-Day Active Recovery\n- Easy jog: 15-20 min at conversational pace (clears metabolic waste)\n- Foam roll quads, hamstrings, calves: 2 min each\n- Hip flexor stretch: 2 × 60 sec each side\n- Avoid heavy loading — no strength training the day after a match\n\n## Return to Full Training\n- Day 2 post-match: Technical training at low-medium intensity\n- Day 3+: Full training and strength sessions permissible',
          },
        ],
      },
    },
  },
}

/* ── Pillar content panel ─────────────────────────────── */
function PillarContent({ sport, pillarId }: { sport: typeof SPORT_DATA[string]; pillarId: string }) {
  const [openLesson, setOpenLesson] = useState<number | null>(0)
  const content = sport.pillars[pillarId]
  if (!content) return null

  return (
    <div className="space-y-8">
      {/* Intro */}
      <p className="text-white/55 text-base leading-relaxed">{content.intro}</p>

      {/* Key points */}
      <div>
        <p className="font-mono text-[10px] text-white/25 uppercase tracking-widest mb-4">Key Principles</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {content.keyPoints.map((pt, i) => (
            <div key={i} className="flex items-start gap-3 p-4 rounded-xl" style={{ background: 'rgba(96,108,56,0.06)', border: '1px solid rgba(96,108,56,0.1)' }}>
              <div className="step-badge shrink-0 mt-0.5">{String(i + 1).padStart(2, '0')}</div>
              <p className="text-white/65 text-sm leading-relaxed">{pt}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Lessons */}
      <div>
        <p className="font-mono text-[10px] text-white/25 uppercase tracking-widest mb-4">Lessons</p>
        <div className="space-y-3">
          {content.lessons.map((lesson, i) => (
            <div key={i} className="rounded-xl overflow-hidden" style={{ border: `1px solid ${openLesson === i ? 'rgba(96,108,56,0.35)' : 'rgba(96,108,56,0.1)'}` }}>
              {/* Header */}
              <button
                onClick={() => setOpenLesson(o => o === i ? null : i)}
                className="w-full flex items-center gap-4 p-4 text-left transition-colors hover:bg-white/[0.02]"
              >
                <div className="step-badge shrink-0">{String(i + 1).padStart(2, '0')}</div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <span className="font-mono text-[9px] uppercase tracking-wider px-2 py-0.5 rounded-full" style={{ color: '#8a9c4a', background: 'rgba(96,108,56,0.1)', border: '1px solid rgba(96,108,56,0.2)' }}>
                      {lesson.type}
                    </span>
                    <span className="flex items-center gap-1 font-mono text-[9px] text-white/25">
                      <Clock size={9} /> {lesson.duration}
                    </span>
                    {!lesson.preview && <Lock size={10} className="text-white/20" />}
                  </div>
                  <p className="text-white/80 text-sm font-medium">{lesson.title}</p>
                </div>
                <ChevronRight size={16} className={`text-white/25 shrink-0 transition-transform ${openLesson === i ? 'rotate-90' : ''}`} />
              </button>

              {/* Body */}
              {openLesson === i && (
                <div className="px-5 pb-5 pt-1 border-t border-[#606C38]/10">
                  {lesson.preview ? (
                    <div className="prose-sm max-w-none">
                      {lesson.body.split('\n').map((line, j) => {
                        if (line.startsWith('## ')) return <h3 key={j} className="text-white/90 font-bold text-sm mt-4 mb-2">{line.slice(3)}</h3>
                        if (line.startsWith('### ')) return <h4 key={j} className="text-[#8a9c4a] font-semibold text-xs mt-3 mb-1.5 uppercase tracking-wider font-mono">{line.slice(4)}</h4>
                        if (line.startsWith('• ')) return <p key={j} className="text-white/55 text-sm leading-relaxed pl-3 border-l border-[#606C38]/20 my-1">{line.slice(2)}</p>
                        if (line.startsWith('**') && line.endsWith('**')) return <p key={j} className="text-white/70 font-semibold text-sm mt-3">{line.slice(2, -2)}</p>
                        if (line.match(/^\d+\./)) return <p key={j} className="text-white/55 text-sm leading-relaxed my-1">{line}</p>
                        if (line === '') return <div key={j} className="h-2" />
                        return <p key={j} className="text-white/55 text-sm leading-relaxed my-1">{line}</p>
                      })}
                    </div>
                  ) : (
                    <div className="text-center py-6">
                      <Lock size={20} className="text-white/15 mx-auto mb-3" />
                      <p className="text-white/35 text-sm mb-4">Sign in to access this lesson</p>
                      <Link to="/auth?mode=signup">
                        <Button size="sm" className="font-semibold text-white" style={{ background: '#606C38' }}>
                          Get Free Access
                        </Button>
                      </Link>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

/* ── Main page ────────────────────────────────────────── */
export default function SportDetailPage() {
  const { slug } = useParams<{ slug: string }>()
  const [activePillar, setActivePillar] = useState('learn')

  const sport = slug ? SPORT_DATA[slug] : null

  if (!sport) {
    return (
      <div style={{ background: '#080C14', minHeight: '100vh' }} className="flex items-center justify-center">
        <div className="text-center">
          <p className="text-white/50 mb-4">Sport not found or not yet available.</p>
          <Link to="/sports">
            <Button style={{ background: '#606C38' }} className="text-white">← Back to Sports</Button>
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div style={{ background: '#080C14', minHeight: '100vh' }}>
      {/* Hero */}
      <section className="relative overflow-hidden pt-16 pb-16 lg:pt-20 lg:pb-20">
        <div className="absolute inset-0 grid-overlay pointer-events-none" />
        <div className="scanline pointer-events-none" />
        <div className="absolute top-0 right-1/4 w-[500px] h-[350px] rounded-full pointer-events-none"
          style={{ background: 'radial-gradient(ellipse, rgba(96,108,56,0.09) 0%, transparent 70%)' }} />

        <div className="relative max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 mb-6 font-mono text-[10px] text-white/25 uppercase tracking-wider">
            <Link to="/sports" className="hover:text-white/50 transition-colors">Sports</Link>
            <ChevronRight size={10} />
            <span className="text-white/50">{sport.name}</span>
          </div>

          <div className="flex items-start gap-6">
            <span className="text-5xl">{sport.icon}</span>
            <div>
              <PillTag className="mb-3">Full Coverage</PillTag>
              <h1 className="text-4xl sm:text-5xl font-black tracking-tight text-white mb-3 leading-tight">
                {sport.name}
              </h1>
              <p className="text-white/50 text-lg max-w-2xl leading-relaxed">{sport.tagline}</p>
            </div>
          </div>

          {/* Key stats */}
          <div className="flex flex-wrap gap-4 mt-8">
            {sport.keyStats.map(stat => (
              <div key={stat.label} className="relative px-4 py-3 rounded-xl" style={{ border: '1px solid rgba(96,108,56,0.18)', background: 'rgba(13,20,32,0.5)' }}>
                <span className="absolute top-0 left-0 w-2 h-2 border-t border-l border-[#606C38]/35" />
                <p className="font-mono text-[9px] text-white/25 uppercase tracking-wider mb-1">{stat.label}</p>
                <p className="text-white/75 text-sm font-medium">{stat.value}</p>
              </div>
            ))}
          </div>
        </div>
        <div className="relative max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 mt-10">
          <NodeLine />
        </div>
      </section>

      {/* Pillar tabs */}
      <div className="sticky top-16 z-30" style={{ background: '#080C14', borderBottom: '1px solid rgba(96,108,56,0.1)' }}>
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-0.5 overflow-x-auto py-1 no-scrollbar">
            {PILLARS.map((pillar, i) => {
              const Icon = pillar.icon
              const active = activePillar === pillar.id
              return (
                <button
                  key={pillar.id}
                  onClick={() => setActivePillar(pillar.id)}
                  className={cn(
                    'flex items-center gap-2 px-4 py-3 text-sm font-medium transition-all whitespace-nowrap shrink-0 border-b-2',
                    active
                      ? 'text-[#8a9c4a] border-[#606C38]'
                      : 'text-white/35 border-transparent hover:text-white/60',
                  )}
                >
                  <div className="step-badge shrink-0 w-5 h-5 text-[9px]">{i + 1}</div>
                  {pillar.label}
                </button>
              )
            })}
          </div>
        </div>
      </div>

      {/* Pillar content */}
      <section className="py-12 lg:py-16">
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl">
            <div className="flex items-center gap-3 mb-8">
              <div className="w-8 h-8 rounded-lg flex items-center justify-center"
                style={{ background: 'rgba(96,108,56,0.1)', border: '1px solid rgba(96,108,56,0.25)' }}>
                <span className="text-[#8a9c4a] text-xs font-bold">{PILLARS.findIndex(p => p.id === activePillar) + 1}</span>
              </div>
              <h2 className="text-xl font-bold text-white">
                {PILLARS.find(p => p.id === activePillar)?.label}
              </h2>
            </div>
            <PillarContent sport={sport} pillarId={activePillar} />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-14 relative overflow-hidden" style={{ background: '#0D1420' }}>
        <div className="absolute inset-0 grid-overlay pointer-events-none" />
        <div className="relative max-w-[1440px] mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl font-black text-white mb-3">
            Track your <span className="text-gradient-olive">{sport.name} training</span>
          </h2>
          <p className="text-white/40 max-w-md mx-auto mb-6 text-sm">
            Sign up free to access all lessons, get a personalised warmup protocol, and track your training with the MotionLab AI coach.
          </p>
          <div className="flex items-center justify-center gap-3 flex-wrap">
            <Link to="/auth?mode=signup">
              <Button size="lg" className="font-bold text-white" style={{ background: '#606C38', border: '1px solid rgba(96,108,56,0.5)' }}>
                Get Started Free <ArrowRight size={16} className="ml-2" />
              </Button>
            </Link>
            <Link to="/sports">
              <Button size="lg" variant="ghost" className="text-white/40 hover:text-white">
                ← All Sports
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
