// The Body Lab uses clean, textbook exercise names ("Bench Press", "Cable Fly")
// that don't always match the free-exercise-db catalog verbatim ("Barbell Bench
// Press - Medium Grip", "Cable Crossover"). Rather than degrade the anatomy UI to
// the catalog's clunkier strings, we keep the nice display names and resolve them
// to the correct DB row through this curated map. Each target below was verified
// by hand against the 873-exercise catalog — no fuzzy guessing (which mislabels,
// e.g. "Bench Press" -> "Bent Press").
//
// Names NOT listed either already match a catalog row exactly (Face Pull, Plank,
// Dead Bug, Good Morning, Pallof Press, Cable Crunch, Reverse Crunch, Russian
// Twist, Hanging Leg Raise, Chin-Up, Leg Press, Romanian/Sumo Deadlift, Butterfly,
// Straight-Arm Pulldown…) or have no catalog equivalent (Nordic Curl, Clamshell,
// Bird Dog, most neck/mobility drills) and fall through to the Groq fallback in
// ExerciseModal, which generates form steps on the fly.

export const EXERCISE_ALIASES: Record<string, string> = {
  'Ab Wheel Rollout': 'Barbell Ab Rollout',
  'Arnold Press': 'Arnold Dumbbell Press',
  'Back Extension': 'Hyperextensions (Back Extensions)',
  'Back Squat': 'Barbell Squat',
  'Band Pull-Apart': 'Band Pull Apart',
  'Barbell Row': 'Bent Over Barbell Row',
  'Bench Press': 'Barbell Bench Press - Medium Grip',
  'Bench Press Lockout': 'Barbell Bench Press - Medium Grip',
  'Bent-Knee Calf Raise': 'Seated Calf Raise',
  'Bent-Over Row': 'Bent Over Barbell Row',
  'Bicycle Crunch': 'Air Bike',
  'Bosu Squat': 'Bodyweight Squat',
  'Bulgarian Split Squat': 'Split Squat with Dumbbells',
  'Cable Curl': 'Standing Biceps Cable Curl',
  'Cable Fly': 'Cable Crossover',
  'Cable Lateral': 'Cable Seated Lateral Raise',
  'Cable Rotation': 'Cable Russian Twists',
  'Calf Press on Leg Press': 'Calf Press On The Leg Press Machine',
  'Close-Grip Bench': 'Close-Grip Barbell Bench Press',
  'Cross-Body Curl': 'Cross Body Hammer Curl',
  'Crunch': 'Crunches',
  'Deadlift': 'Barbell Deadlift',
  'Decline Sit-Up': 'Crunches',
  'Diamond Push-Up': 'Push-Ups - Close Triceps Position',
  'Dip': 'Dips - Triceps Version',
  'Dumbbell Curl': 'Dumbbell Bicep Curl',
  'Dumbbell Fly': 'Dumbbell Flyes',
  'EZ-Bar Reverse Curl': 'Reverse Barbell Curl',
  'Farmer Carry': "Farmer's Walk",
  'Front Raise': 'Front Dumbbell Raise',
  'Glute Bridge': 'Barbell Glute Bridge',
  'Hack Squat': 'Barbell Hack Squat',
  'Hammer Curl': 'Hammer Curls',
  'Hanging Knee Raise': 'Hanging Leg Raise',
  'Hip Thrust': 'Barbell Hip Thrust',
  'Incline Curl': 'Incline Dumbbell Curl',
  'Incline Press': 'Barbell Incline Bench Press - Medium Grip',
  'Jump Rope': 'Rope Jumping',
  'Landmine Twist': "Landmine 180's",
  'Lat Pulldown': 'Wide-Grip Lat Pulldown',
  'Lateral Raise': 'Side Lateral Raise',
  'Lateral Step-Up': 'Barbell Step Ups',
  'Leg Extension': 'Leg Extensions',
  'Leg Extension (final 30°)': 'Leg Extensions',
  'Leg Press Calf Raise': 'Calf Press On The Leg Press Machine',
  'Lying Leg Curl': 'Lying Leg Curls',
  'Machine Lateral': 'Side Lateral Raise',
  'Narrow Squat': 'Barbell Squat',
  'Neutral-Grip Chin-Up': 'Chin-Up',
  'Overhead Press': 'Standing Military Press',
  'Overhead Triceps Extension': 'Standing Overhead Barbell Triceps Extension',
  'Pull-Up': 'Pullups',
  'Push-Up': 'Pushups',
  'Push-Up Plus': 'Pushups',
  'Pushdown': 'Triceps Pushdown',
  'Rear Delt Fly': 'Cable Rear Delt Fly',
  'Reverse Curl': 'Reverse Barbell Curl',
  'Reverse Grip Pushdown': 'Reverse Grip Triceps Pushdown',
  'Reverse Pec Deck': 'Reverse Machine Flyes',
  'Reverse Wrist Curl': 'Palms-Down Dumbbell Wrist Curl Over A Bench',
  'Seated Cable Row': 'Seated Cable Rows',
  'Shrug': 'Barbell Shrug',
  'Side Plank': 'Side Bridge',
  'Single-Arm Row': 'One-Arm Dumbbell Row',
  'Single-Leg Press': 'Leg Press',
  'Skull Crusher': 'EZ-Bar Skullcrusher',
  'Squat': 'Barbell Squat',
  'Standing Calf Raise': 'Standing Calf Raises',
  'Step-Up': 'Barbell Step Ups',
  'Sumo Squat': 'Plie Dumbbell Squat',
  'Terminal Knee Extension': 'Leg Extensions',
  'Towel Pull-Up': 'Pullups',
  'Upright Row': 'Upright Barbell Row',
  'Walking Lunge': 'Bodyweight Walking Lunge',
  'Wide-Stance Leg Press': 'Leg Press',
  'Woodchop': 'Standing Cable Wood Chop',
  'Wrist Curl': 'Palms-Up Barbell Wrist Curl Over A Bench',
}

// Returns the catalog name to look up for a given display name.
export function resolveExerciseName(displayName: string): string {
  return EXERCISE_ALIASES[displayName] ?? displayName
}
